In [25]:
#One Dimensional Array
import numpy as np
a=np.array([7,8,9,10,11])
print(f'{a}\n{"Object Type:":>12}  {type(a)}\n{"Data Type:":>12}  {a.dtype}\n{"Shape:":>12} \
{a.shape}\n{"Dimension:":>12}  {a.ndim}\n{"Array Size":>12}  {a.size}')
a1=np.array([a])
print(a1, a1.shape)
print("Dim =",a1.ndim,",","Size =",a1.size)

[ 7  8  9 10 11]
Object Type:  <class 'numpy.ndarray'>
  Data Type:  int32
      Shape: (5,)
  Dimension:  1
  Array Size  5
[[ 7  8  9 10 11]] (1, 5)
Dim = 2 , Size = 5


In [15]:
#Two Dimensional Array
b=np.array([[1.0,2,3,4,5],[8,9,10,11,12.1]])
print(f'{b}\n{"Object Type":>12}  {type(b)}\n{"Data Type:":>12}  {b.dtype}\n{"Shape:":>12} \
{b.shape}\n{"Dimension:":>12}  {b.ndim}\n{"Array Size:":>12}  {b.size}')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.1]]
 Object Type  <class 'numpy.ndarray'>
  Data Type:  float64
      Shape: (2, 5)
  Dimension:  2
 Array Size:  10


In [27]:
#Three Dimensional Array
c=np.array([[[1,2,3],[4,5,6],[-1,-2,-3]],[[7,8,9],[10,11,12],[-4,-5,-6]]])
print(f'{c}\n{"Object Type":>12}  {type(c)}\n{"Data Type:":>12}  {c.dtype}\n{"Shape:":>12} \
{c.shape}\n{"Dimension:":>12}  {c.ndim}\n{"Array Size:":>12}  {c.size}')

[[[ 1  2  3]
  [ 4  5  6]
  [-1 -2 -3]]

 [[ 7  8  9]
  [10 11 12]
  [-4 -5 -6]]]
 Object Type  <class 'numpy.ndarray'>
  Data Type:  int32
      Shape: (2, 3, 3)
  Dimension:  3
 Array Size:  18


In [29]:
c1=np.array([[[1,2,3,4],[6,7,8,9]]])
print(f'{c1}\n{"Object Type":>12}  {type(c1)}\n{"Data Type:":>12}  {c1.dtype}\n{"Shape:":>12} \
{c1.shape}\n{"Dimension:":>12}  {c1.ndim}\n{"Array Size:":>12}  {c1.size}')

[[[1 2 3 4]
  [6 7 8 9]]]
 Object Type  <class 'numpy.ndarray'>
  Data Type:  int32
      Shape: (1, 2, 4)
  Dimension:  3
 Array Size:  8


In [30]:
c2=np.array([[[1,2,3,4,5,6]]])
print(f'{c2}\n{"Object Type":>12}  {type(c2)}\n{"Data Type:":>12}  {c2.dtype}\n{"Shape:":>12} \
{c2.shape}\n{"Dimension:":>12}  {c2.ndim}\n{"Array Size:":>12}  {c2.size}')

[[[1 2 3 4 5 6]]]
 Object Type  <class 'numpy.ndarray'>
  Data Type:  int32
      Shape: (1, 1, 6)
  Dimension:  3
 Array Size:  6


In [8]:
import numpy as np
a_zeros= np.zeros((1,5), dtype=int)
print(a_zeros)
a_ones= np.ones((2,4), dtype=int)
print(a_ones)
a_seven= np.full((2,3),7)
print(a_seven)
print(np.eye(3))

[[0 0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
a_rand=np.random.random((2,3,4))
print(f'{a_rand}\n{a_rand.dtype}')

[[[0.55672824 0.53775221 0.59519332 0.30910325]
  [0.81964138 0.22514558 0.75914071 0.90216183]
  [0.15722546 0.86962581 0.30641962 0.72910569]]

 [[0.53529791 0.9001048  0.85143396 0.87529347]
  [0.10727355 0.03386976 0.64479615 0.84707864]
  [0.98857094 0.86720891 0.91274405 0.49411771]]]
float64


In [14]:
c1=np.array([[[1,2,3,4],[6,7,8,9]]])
print(c1.shape)
print(c1[0,1,3])
print(c1[0,0,2])

(1, 2, 4)
9
3


In [18]:
c=np.array([[[1,2,3],[4,5,6],[-1,-2,-3]],[[7,8,9],[10,11,12],[-4,-5,-6]]])
print(c.shape)
print(c.ndim)
print(c.size)
print(c[0,2,0])
print(c[1,1,2])

(2, 3, 3)
3
18
-1
12


In [20]:
l=[]
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')
print()

#Flattening
print(np.array(c.flat))

[1, 2, 3, 4, 5, 6, -1, -2, -3, 7, 8, 9, 10, 11, 12, -4, -5, -6]
[ 1  2  3  4  5  6 -1 -2 -3  7  8  9 10 11 12 -4 -5 -6]

[ 1  2  3  4  5  6 -1 -2 -3  7  8  9 10 11 12 -4 -5 -6]


In [24]:
g=np.arange(21)
print(g)
print(g.reshape(1,3,7))
print(g.reshape(3,1,7))
print(g.reshape(7,1,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]
[[[ 0  1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]]]
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]

 [[12 13 14]]

 [[15 16 17]]

 [[18 19 20]]]
